export enum Repository {
  USER_REPOSITORY = 'USER_REPOSITORY',
  PROFILE_REPOSITORY = 'PROFILE_REPOSITORY',
  JOB_REPOSITORY = 'JOB_REPOSITORY',
}

export enum Connection {
  DATABASE_CONNECTION = 'DATABASE_CONNECTION',
}
